name: "Discord"

on:
  workflow_call:
    inputs:
      MESSAGE:
        required: true
        description: "Message"
        type: string
    secrets:
      DISCORD_WEBHOOK:
        required: true
jobs:

  Discord:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: ${{ inputs.MESSAGE }}