name: "Docker Build & Push"

on:
  workflow_call:
    inputs:
      USERNAME:
        required: true
        description: "Github username"
        type: string
      CONTEXT:
        required: false
        description: "Dockerfile path"
        default: "./"
        type: string
      DOCKERFILE_NAME:
        required: false
        description: "Dockerfile filename"
        default: "Dockerfile"
        type: string
      IMAGE_REPO:
        required: true
        description: "Image repository"
        type: string
      IMAGE_NAME:
        required: true
        description: "Image Name"
        type: string
      PUSH:
        required: false
        description: "Push on repository"
        default: true
        type: boolean
      TAG:
        required: true
        description: "Discord Webhook"
        type: string
      PLATFORM:
        required: false
        description: "CPU Architecture"
        default: "linux/amd64, linux/arm64, linux/arm/v6, linux/arm/v7"
        type: string
      LATEST:
        required: false
        description: "Build Latest image"
        default: false
        type: boolean
      LATEST_DEV:
        required: false
        description: "Build Latest Dev image"
        default: true
        type: boolean
    secrets:
      GH_TOKEN:
        required: true

jobs:

  #################################################################################################################
  # SEMANTIC RELEASE
  Build-Push-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #################################################################################################################
      # SETUP DOCKER
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/MyElectricalData
          username: ${{ inputs.USERNAME }}
          password: ${{ inputs.GH_TOKEN }}


      #################################################################################################################
      # VERSION
      - name: Build tags variable
        shell: bash
        run: |
          IMAGE_PATH="${{ inputs.IMAGE_REPO }}/${{ inputs.IMAGE_NAME }}"
          TAGS="${IMAGE_PATH}:${{ inputs.TAG }},"
          if [ "${{ inputs.LATEST }}" == "true" ]; then
            TAGS="${TAGS}${IMAGE_PATH}:latest,"
          fi
          if [ "${{ inputs.LATEST_DEV }}" == "true" ]; then
            TAGS="${TAGS}${IMAGE_PATH}:latest-dev,"
          fi
          echo "TAGS=${TAGS}" >> "$GITHUB_ENV"
          echo "Build : ${TAGS}"

      - name: Build and push ${{ inputs.VERSION }} / latest-dev
        uses: docker/build-push-action@v5
        with:
          file: ${{ inputs.DOCKERFILE_NAME }}
          platforms: ${{ inputs.PLATFORM }}
          context: ${{ inputs.CONTEXT }}
          push: ${{ inputs.PUSH }}
          tags: |
            ${{ env.TAGS }}